### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'results'

### ISSUE THREAD

**Issue by xuningwang** [uber/causalml#359] opened 2021-07-16 08:32 UTC
**Describe the bug**

i train a UpliftRandomForestClassifier, 

the code: 

```
forest = UpliftRandomForestClassifier(n_estimators=500, 
                                    evaluationFunction='KL',
                                    max_features=20,
                                    random_state=123,
                                    min_samples_leaf = 300,
                                    control_name = 'control',
                                    n_jobs = 4
                                    )
forest.fit(X = feature_train.values, treatment = ty_train['treatment'].values, y = ty_train['zixun_ind'].values)
forest.predict(X = feature_train.values)
```

model trained and when i predict: the following error accurs:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-701a1ea15d81> in <module>
----> 1 forest.predict(X = feature_train.values)

~/miniconda3/lib/python3.6/site-packages/sklearn/utils/_testing.py in wrapper(*args, **kwargs)
    325             with warnings.catch_warnings():
    326                 warnings.simplefilter("ignore", self.category)
--> 327                 return fn(*args, **kwargs)
    328 
    329         return wrapper

~/miniconda3/lib/python3.6/site-packages/causalml/inference/tree/models.py in predict(self, X, full_output)
   1332         for tree_i in range(len(self.uplift_forest)):
   1333 
-> 1334             _, _, _, y_pred_full = self.uplift_forest[tree_i].predict(X=X, full_output=True)
   1335 
   1336             if tree_i == 0:

~/miniconda3/lib/python3.6/site-packages/causalml/inference/tree/models.py in predict(self, X, full_output)
    488         upliftScores = []
    489         for xi in range(len(X)):
--> 490             pred_leaf, upliftScore = self.classify(X[xi], self.fitted_uplift_tree, dataMissing=False)
    491             # Predict under uplift optimal treatment
    492             opt_treat = max(pred_leaf, key=pred_leaf.get)

~/miniconda3/lib/python3.6/site-packages/causalml/inference/tree/models.py in classify(observations, tree, dataMissing)
   1160             return classifyWithMissingData(observations, tree)
   1161         else:
-> 1162             return classifyWithoutMissingData(observations, tree)
   1163 
   1164 

~/miniconda3/lib/python3.6/site-packages/causalml/inference/tree/models.py in classifyWithoutMissingData(observations, tree)
   1092                 The results in the leaf node.
   1093             '''
-> 1094             if tree.results is not None:  # leaf
   1095                 return tree.results, tree.upliftScore
   1096             else:

AttributeError: 'NoneType' object has no attribute 'results'

**Comment by paullo0106** [comment] 2021-07-19 04:08
@xuningwang Thanks for reporting the issue, here are some questions for debugging into this:

1. Are you on the latest version 0.10 and would you get any errors with this [uplift tree notebook](https://github.com/uber/causalml/blob/master/examples/uplift_tree_visualization.ipynb)? 
2. If we spot check one of the trees by running below, what output would you get?

```
forest.uplift_forest[0].fitted_uplift_tree.results
```

```
from causalml.inference.tree import uplift_tree_string
uplift_tree_string(forest.uplift_forest[0].fitted_uplift_tree, feature_train.columns)
```

**Comment by paullo0106** [comment] 2023-08-19 01:59
closing as we can't reproduce the issue

**Closed by paullo0106** 2023-08-19 01:59 UTC
Labels: bug
