### ISSUE TITLE
No module named 'causalml.inference.tree.causaltree'

### ISSUE THREAD

**Issue by alittlesong** [uber/causalml#206] opened 2020-07-01 03:47 UTC
**Describe the bug**
I installed causalml from pip and got the error of "ModuleNotFoundError: No module named 'causalml.inference.tree.causaltree'" when importing the following functions/packages:

from causalml.dataset import make_uplift_classification
from causalml.inference.tree import UpliftTreeClassifier, UpliftRandomForestClassifier
from causalml.inference.tree import uplift_tree_string, uplift_tree_plot

I am able to import meta learner packages like:

from causalml.inference.meta import LRSRegressor
from causalml.inference.meta import XGBTRegressor, MLPTRegressor
from causalml.inference.meta import BaseXRegressor, BaseRRegressor, BaseSRegressor, BaseTRegressor
from causalml.match import NearestNeighborMatch, MatchOptimizer, create_table_one
from causalml.propensity import ElasticNetPropensityModel

**To Reproduce**
pip install causalml

**Expected behavior**
import causal tree packages successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/11971926/86200646-2141fe80-bb12-11ea-8ee9-16aa2be431f6.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Python Version: 3.7.6
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): `pandas==1.0.4`, `scikit-learn==0.22`, `cython==0.29.15`, 'numpy = 1.18.2']

**Additional context**
I tried to clone the repository and compile the Cython modules myself from the source code using python setup.py build_ext --inplace (follwing https://github.com/uber/causalml/issues/148), I did see some warnings "Using deprecated NumPy API, disable it by", but I still have issue to import causal tree.

**Comment by jeongyoonlee** [comment] 2020-07-02 18:16
Thanks for reporting the issue, @alittlesong. I just tried it with the same versions of packages, but couldn't reproduce the error (see the screenshot below). 
<img width="725" alt="Screen Shot 2020-07-02 at 11 11 43 AM" src="https://user-images.githubusercontent.com/3359887/86395410-10e66c80-bc55-11ea-8556-1d9ab1ea3856.png">

Could you try to remove any cached or previous installation of `causalml` and install again as follows?
```bash
# from somewhere not in the causalml source directory
$ pip uninstall causalml 
$ pip install --no-cache-dir -U causalml
```

Please let me know if it helps.

**Comment by jeongyoonlee** [comment] 2020-09-16 17:25
Hi, @alittlesong, were you able to resolve the issue?

**Comment by adilahiri** [comment] 2020-11-20 22:36
@alittlesong would like to know if you were able to resolve the issue, I made sure the requirements were fine on my end but still getting the error.

**Comment by vincewu51** [comment] 2023-08-19 00:39
close this for now. Feel free to reopen is there is still an error.

**Closed by vincewu51** 2023-08-19 00:39 UTC
Labels: installation
