### ISSUE TITLE
AttributeError: 'int' object has no attribute 'clear'

### ISSUE THREAD

**Issue by dandan0503** [uber/causalml#95] opened 2019-12-05 09:35 UTC
hi,
when i run example,i get the follow error
![image](https://user-images.githubusercontent.com/22792438/70222350-e7c83100-1784-11ea-9e98-dfb3a8ee5018.png)
please give advice or comments，thank you~

**Comment by dandan0503** [comment] 2019-12-05 09:35
In [4]: df_train, df_test = train_test_split(df, test_size=0.2, random_state=111)

In [5]: uplift_model = UpliftRandomForestClassifier(control_name='control')

In [6]: uplift_model.fit(df_train[x_names].values,
   ...:                  treatment=df_train['treatment_group_key'].values,
   ...:                  y=df_train['conversion'].values)



In [7]:

In [7]:

In [7]: y_pred = uplift_model.predict(df_test[x_names].values)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-81543bba437e> in <module>
----> 1 y_pred = uplift_model.predict(df_test[x_names].values)

/data/program/anaconda3/lib/python3.7/site-packages/sklearn/utils/testing.py in wrapper(*args, **kwargs)
    350         @wraps(fn)
    351         def wrapper(*args, **kwargs):
--> 352             clean_warning_registry()
    353             with warnings.catch_warnings():
    354                 warnings.simplefilter("ignore", self.category)

/data/program/anaconda3/lib/python3.7/site-packages/sklearn/utils/testing.py in clean_warning_registry()
    764     for mod_name, mod in list(sys.modules.items()):
    765         if hasattr(mod, reg):
--> 766             getattr(mod, reg).clear()
    767
    768

AttributeError: 'int' object has no attribute 'clear'

**Comment by t-tte** [comment] 2019-12-05 17:43
Hey @dandan0503 - which version of causalml and scikit-learn are you using?

**Comment by dandan0503** [comment] 2019-12-06 10:23
scikit-learn 0.21.3

**Comment by paullo0106** [comment] 2019-12-06 23:43
Looks like it happened particularly on your `tensorboard pywrap_tensorflow.py` module, I found that there is defensive code in the recent version `(scikit-learn=0.22)` of [sklearn.utils.testing.py](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/_testing.py#L616) to avoid this:

```
def clean_warning_registry():
    """Clean Python warning registry for easier testing of warning messages.
    When changing warning filters this function is not necessary with
    Python3.5+, as __warningregistry__ will be re-set internally.
    See https://bugs.python.org/issue4180 and
    https://bugs.python.org/issue21724 for more details.
    """
    for mod in sys.modules.values():
        registry = getattr(mod, "__warningregistry__", None)
        if registry is not None:
            registry.clear()
```

**Comment by t-tte** [comment] 2019-12-09 11:26
Thanks for chiming in @paullo0106!

@dandan0503 - does updating to scikit-learn >= 0.22 also resolve your problem? Unfortunately I'm not able to replicate the issue with scikit-learn 0.21.3.

In any case, the current working hypothesis is that the problem is to do with the ignore_warnings function, which we may be able to do away with entirely. cc @zhenyuz0500

**Comment by jeongyoonlee** [comment] 2020-04-14 22:15
Let's close this for now because @t-tte couldn't replicate the issue with latest `scikit-learn>=0.22`, which is required.

**Closed by jeongyoonlee** 2020-04-14 22:15 UTC
Labels: bug
